<?php

namespace Database\Seeders;

use App\Models\Faculty;
use Illuminate\Database\Seeder;

class FacultySeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->faculty() as $record) {
            Faculty::updateOrCreate(
                ['email' => $record['email']],
                $record
            );
        }
    }

    private function faculty(): array
    {
        return [
            ['name' => 'Mr. Daniel Flores', 'title' => 'Instructor', 'department' => 'BS Computer Science', 'bio' => 'Mr. Daniel Flores teaches database management and software engineering principles.', 'email' => 'daniel.flores@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Prof. John Reyes', 'title' => 'Professor', 'department' => 'BS Information Technology', 'bio' => 'Prof. John Reyes focuses on web development, cybersecurity, and network infrastructure.', 'email' => 'john.reyes@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Ms. Camille Navarro', 'title' => 'Assistant Professor', 'department' => 'BS Information Technology', 'bio' => 'Ms. Camille Navarro specializes in mobile application development and UI/UX design.', 'email' => 'camille.navarro@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Engr. Carla Mendoza', 'title' => 'Assistant Professor', 'department' => 'BS Civil Engineering', 'bio' => 'Engr. Carla Mendoza teaches structural analysis and construction management.', 'email' => 'carla.mendoza@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Engr. Michael Torres', 'title' => 'Senior Lecturer', 'department' => 'BS Mechanical Engineering', 'bio' => 'Engr. Michael Torres specializes in thermodynamics and fluid mechanics.', 'email' => 'michael.torres@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Engr. Kevin Bautista', 'title' => 'Laboratory Coordinator', 'department' => 'BS Mechanical Engineering', 'bio' => 'Engr. Kevin Bautista manages engineering laboratory operations and safety protocols.', 'email' => 'kevin.bautista@nu-lipa.edu.ph', 'image' => 'faculty/besdpc61fgnj8pdssyym'],
            ['name' => 'Dr. Sophia Ramirez', 'title' => 'Department Chairperson', 'department' => 'BS Nursing', 'bio' => 'Dr. Sophia Ramirez has extensive experience in community health nursing and clinical practice.', 'email' => 'sophia.ramirez@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Dr. Rachel Aquino', 'title' => 'Professor', 'department' => 'BS Nursing', 'bio' => 'Dr. Rachel Aquino focuses on pediatric nursing and maternal health care.', 'email' => 'rachel.aquino@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Ms. Angela Villanueva', 'title' => 'Instructor', 'department' => 'BS Accountancy', 'bio' => 'Ms. Angela Villanueva teaches financial accounting and taxation law.', 'email' => 'angela.villanueva@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Dr. Anthony Cruz', 'title' => 'Research Coordinator', 'department' => 'BS Psychology', 'bio' => 'Dr. Anthony Cruz conducts research in behavioral psychology and cognitive science.', 'email' => 'anthony.cruz@nu-lipa.edu.ph', 'image' => 'faculty/ndq28pz1r4ieezf5m6nx'],
            ['name' => 'Prof. Patricia Gomez', 'title' => 'Faculty Member', 'department' => 'BS Education', 'bio' => 'Prof. Patricia Gomez specializes in curriculum development and educational technology.', 'email' => 'patricia.gomez@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Prof. Maria Teresa Reyes', 'title' => 'Professor', 'department' => 'Bachelor of Multimedia Arts', 'bio' => 'Prof. Reyes is a senior faculty member in Business Administration with expertise in marketing, entrepreneurship, and strategic management. She has published several research papers and serves as an adviser to student organizations.', 'email' => 'maria.teresa.reyes@nu-lipa.edu.ph', 'image' => 'faculty/msm2a8ota86b1lzpeb6n'],
            ['name' => 'Prof. Liza Evangelista', 'title' => 'Associate Professor', 'department' => 'BS Computer Science', 'bio' => 'Prof. Liza Evangelista specializes in machine learning and data science. She has published several research papers on neural networks and AI applications in education.', 'email' => 'liza.evangelista@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Mr. Arjay Panganiban', 'title' => 'Instructor', 'department' => 'BS Computer Science', 'bio' => 'Mr. Arjay Panganiban teaches programming fundamentals, object-oriented programming, and software engineering. He has industry experience in full-stack development.', 'email' => 'arjay.panganiban@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Ms. Hazel Tolentino', 'title' => 'Laboratory Instructor', 'department' => 'BS Computer Science', 'bio' => 'Ms. Hazel Tolentino oversees computer laboratory sessions and teaches data structures and algorithms. She holds a master degree in computer science.', 'email' => 'hazel.tolentino@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Engr. Marco Dela Cruz', 'title' => 'Senior Lecturer', 'department' => 'BS Information Technology', 'bio' => 'Engr. Marco Dela Cruz specializes in network administration, cybersecurity, and cloud computing. He brings over 10 years of industry experience to the classroom.', 'email' => 'marco.delacruz@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Ms. Jessa Buenaventura', 'title' => 'Instructor', 'department' => 'BS Information Technology', 'bio' => 'Ms. Jessa Buenaventura teaches system analysis and design, database management, and IT project management. She is passionate about developing tech-savvy graduates.', 'email' => 'jessa.buenaventura@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Engr. Nathan Soriano', 'title' => 'Associate Professor', 'department' => 'BS Civil Engineering', 'bio' => 'Engr. Nathan Soriano specializes in geotechnical engineering and foundation design. He has worked on major infrastructure projects across Luzon.', 'email' => 'nathan.soriano@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Engr. Pamela Aguilar', 'title' => 'Instructor', 'department' => 'BS Civil Engineering', 'bio' => 'Engr. Pamela Aguilar teaches reinforced concrete design and transportation engineering. She is a licensed civil engineer with field experience in road construction.', 'email' => 'pamela.aguilar@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Arch. Ricardo Salazar', 'title' => 'Department Chairperson', 'department' => 'BS Architecture', 'bio' => 'Arch. Ricardo Salazar leads the Architecture department with over 15 years of professional practice. He specializes in sustainable and green architecture design.', 'email' => 'ricardo.salazar@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Arch. Diane Castillo', 'title' => 'Assistant Professor', 'department' => 'BS Architecture', 'bio' => 'Arch. Diane Castillo teaches architectural design, history of architecture, and urban planning. She completed her master degree in architecture from UP Diliman.', 'email' => 'diane.castillo@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Arch. Felix Manalo', 'title' => 'Instructor', 'department' => 'BS Architecture', 'bio' => 'Arch. Felix Manalo specializes in interior architecture and environmental design. He has collaborated on award-winning residential and commercial projects.', 'email' => 'felix.manalo@nu-lipa.edu.ph', 'image' => 'faculty/ofudphyvbvjxr4dhzjrk'],
            ['name' => 'Prof. Katrina Rivera', 'title' => 'Department Chairperson', 'department' => 'Bachelor of Multimedia Arts', 'bio' => 'Prof. Katrina Rivera leads the Multimedia Arts department with expertise in digital illustration, animation, and visual storytelling. She is a multi-awarded graphic designer.', 'email' => 'katrina.rivera@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Mr. Renz Domingo', 'title' => 'Instructor', 'department' => 'Bachelor of Multimedia Arts', 'bio' => 'Mr. Renz Domingo teaches 2D and 3D animation, video production, and motion graphics. He has worked as a freelance animator for international clients.', 'email' => 'renz.domingo@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Ms. Mariz Enriquez', 'title' => 'Laboratory Instructor', 'department' => 'Bachelor of Multimedia Arts', 'bio' => 'Ms. Mariz Enriquez oversees multimedia labs and teaches digital photography, photo manipulation, and UI/UX design principles.', 'email' => 'mariz.enriquez@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Prof. Leah Concepcion', 'title' => 'Associate Professor', 'department' => 'BS Nursing', 'bio' => 'Prof. Leah Concepcion specializes in medical-surgical nursing and nursing informatics. She has extensive clinical experience in tertiary hospitals.', 'email' => 'leah.concepcion@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Ms. Christine Bernardo', 'title' => 'Clinical Instructor', 'department' => 'BS Nursing', 'bio' => 'Ms. Christine Bernardo supervises nursing students during clinical duties and teaches maternal and child health nursing. She is a registered nurse with ICU experience.', 'email' => 'christine.bernardo@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Mr. Carlo Resurreccion', 'title' => 'Instructor', 'department' => 'BS Nursing', 'bio' => 'Mr. Carlo Resurreccion teaches community health nursing, public health, and epidemiology. He has conducted community outreach programs in Batangas.', 'email' => 'carlo.resurreccion@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Dr. Kevin Dimaculangan', 'title' => 'Department Chairperson', 'department' => 'BS Medical Technology', 'bio' => 'Dr. Kevin Dimaculangan leads the Medical Technology department with expertise in clinical chemistry and hematology. He holds a doctorate in medical science.', 'email' => 'kevin.dimaculangan@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Ms. Nicole Bernal', 'title' => 'Instructor', 'department' => 'BS Medical Technology', 'bio' => 'Ms. Nicole Bernal teaches clinical microbiology, parasitology, and immunology. She is a registered medical technologist with hospital laboratory experience.', 'email' => 'nicole.bernal@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Mr. Adrian Lugtu', 'title' => 'Laboratory Coordinator', 'department' => 'BS Medical Technology', 'bio' => 'Mr. Adrian Lugtu manages the medical technology laboratory and teaches histopathology and blood banking. He is passionate about advancing diagnostic science.', 'email' => 'adrian.lugtu@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Prof. Hannah Macapagal', 'title' => 'Associate Professor', 'department' => 'BS Psychology', 'bio' => 'Prof. Hannah Macapagal specializes in clinical and counseling psychology. She provides psychological counseling services and teaches abnormal psychology and psychopathology.', 'email' => 'hannah.macapagal@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Ms. Melissa Pangilinan', 'title' => 'Instructor', 'department' => 'BS Psychology', 'bio' => 'Ms. Melissa Pangilinan teaches developmental psychology, social psychology, and psychological testing. She advocates for mental health awareness on campus.', 'email' => 'melissa.pangilinan@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'CPA. Ramon Abalos', 'title' => 'Department Chairperson', 'department' => 'BS Accountancy', 'bio' => 'CPA. Ramon Abalos leads the Accountancy department with expertise in financial reporting, taxation, and auditing. He is a CPA board topnotcher and review lecturer.', 'email' => 'ramon.abalos@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'CPA. Stella Lacson', 'title' => 'Associate Professor', 'department' => 'BS Accountancy', 'bio' => 'CPA. Stella Lacson teaches advanced financial accounting, cost accounting, and management advisory services. She has extensive experience in public accounting.', 'email' => 'stella.lacson@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Ms. Janine Magno', 'title' => 'Instructor', 'department' => 'BS Accountancy', 'bio' => 'Ms. Janine Magno teaches financial accounting, business mathematics, and accounting information systems. She is pursuing CPA licensure and a master degree.', 'email' => 'janine.magno@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Prof. Victor Gonzales', 'title' => 'Associate Professor', 'department' => 'BSBA Financial Management', 'bio' => 'Prof. Victor Gonzales specializes in investment analysis, corporate finance, and financial markets. He previously worked as a financial analyst in a multinational company.', 'email' => 'victor.gonzales@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Ms. Queenie Delos Santos', 'title' => 'Instructor', 'department' => 'BSBA Financial Management', 'bio' => 'Ms. Queenie Delos Santos teaches financial management, business finance, and banking and finance. She is a licensed financial advisor with expertise in personal finance.', 'email' => 'queenie.delossantos@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Prof. Lorenz Dela Pena', 'title' => 'Department Chairperson', 'department' => 'BS Tourism Management', 'bio' => 'Prof. Lorenz Dela Pena leads the Tourism department with expertise in hospitality management and ecotourism. He has consulted for local government tourism offices.', 'email' => 'lorenz.delapena@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Ms. Camille Perez', 'title' => 'Instructor', 'department' => 'BS Tourism Management', 'bio' => 'Ms. Camille Perez teaches tour guiding, travel agency operations, and tourism marketing. She has hands-on experience working with travel agencies in Manila.', 'email' => 'camille.perez@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Mr. Bryan Gutierrez', 'title' => 'Instructor', 'department' => 'BS Tourism Management', 'bio' => 'Mr. Bryan Gutierrez teaches food and beverage management, front office operations, and events management. He is a certified TESDA trainer in hospitality services.', 'email' => 'bryan.gutierrez@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Prof. Tricia Ramirez', 'title' => 'Associate Professor', 'department' => 'BSBA Marketing Management', 'bio' => 'Prof. Tricia Ramirez specializes in digital marketing, brand management, and consumer behavior. She has worked with top advertising firms and FMCG companies.', 'email' => 'tricia.ramirez@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Mr. Aldrin De Leon', 'title' => 'Instructor', 'department' => 'BSBA Marketing Management', 'bio' => 'Mr. Aldrin De Leon teaches principles of marketing, retail management, and marketing research. He is an entrepreneur and marketing practitioner.', 'email' => 'aldrin.deleon@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Ms. Maricel Valdez', 'title' => 'Senior High School Teacher', 'department' => 'SHS', 'bio' => 'Ms. Maricel Valdez handles core subjects including Oral Communication, Reading and Writing, and Komunikasyon at Pananaliksik. She is a dedicated educator with 8 years of teaching experience.', 'email' => 'maricel.valdez@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Mr. Francis Lacson', 'title' => 'Senior High School Teacher', 'department' => 'SHS', 'bio' => 'Mr. Francis Lacson teaches Business Mathematics, Applied Economics, and Organization and Management for ABM students. He is a licensed professional teacher.', 'email' => 'francis.lacson@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Ms. Bianca Navarro', 'title' => 'Senior High School Teacher', 'department' => 'SHS', 'bio' => 'Ms. Bianca Navarro handles General Biology, Earth and Life Science, and Statistics and Probability for STEM students. She fosters critical thinking and scientific inquiry.', 'email' => 'bianca.navarro@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Mr. Jose Dela Torre', 'title' => 'Senior High School Teacher', 'department' => 'SHS', 'bio' => 'Mr. Jose Dela Torre teaches Philippine Politics and Governance, Introduction to World Religions, and Creative Writing for HUMSS students.', 'email' => 'jose.delatorre@nu-lipa.edu.ph', 'image' => null],
            ['name' => 'Ms. Ana Villafuerte', 'title' => 'Senior High School Coordinator', 'department' => 'SHS', 'bio' => 'Ms. Ana Villafuerte coordinates the Senior High School department and handles PE and Health, Personal Development, and Earth Science. She has a master degree in education.', 'email' => 'ana.villafuerte@nu-lipa.edu.ph', 'image' => null],
        ];
    }
}
