<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body   { font-family: DejaVu Sans, sans-serif; margin: 40px; color: #1a1a2e; }
  .header{ text-align:center; border-bottom:2px solid #3b82f6; padding-bottom:20px; margin-bottom:30px; }
  .name  { font-size:24px; font-weight:bold; margin:10px 0 5px; }
  .detail{ font-size:13px; color:#666; margin:4px 0; }
  .bio   { margin-top:20px; font-style:italic; color:#444; line-height:1.6; }
  .footer{ margin-top:40px; font-size:10px; color:#aaa; text-align:center; }
  img.photo{ width:120px; height:120px; border-radius:60px; object-fit:cover; border:3px solid #3b82f6; }
</style>
</head>
<body>
  <div class="header">
    <p style="font-size:20px;font-weight:bold;color:#1d4ed8">Sinag-Bughaw</p>
    <p style="font-size:12px;color:#666">NU Lipa · Digital Yearbook 2026</p>
  </div>
  <div style="text-align:center">
    @if($user->profile_picture)
      <img class="photo" src="{{ storage_path('app/public/' . $user->profile_picture) }}">
    @endif
    <div class="name">{{ $user->name }}</div>
    <div class="detail">{{ $user->student_id }}</div>
    <div class="detail">{{ $user->course }}</div>
    @if($user->section)
      <div class="detail">Section: {{ $user->section->name }}</div>
    @endif
    @if($user->bio)
      <div class="bio">"{{ $user->bio }}"</div>
    @endif
  </div>
  <div class="footer">Generated by Sinag-Bughaw · {{ now()->format('Y') }}</div>
</body>
</html>